name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Testleri çalıştır
      run: |
        python -m unittest discover

    - name: Simüle dağıtım
      if: success()
      run: echo "Testler başarılı. Deploy hazır."